license_type: MIT
license_name: MIT
is_open_source: true
marketplace_url: https://github.com/robobrainstorm/rb-mmx-optimizer
open_source_repository: https://github.com/robobrainstorm/rb-mmx-optimizer
